import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "./comps/Header";

const pop = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "test next 13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pop.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
